#!/bin/sh

rootdir=/home/ec2-user
exec=$rootdir/openresty-tester.pl
user=ec2-user
logfile=$rootdir/openresty-tester.log
run="sudo -u $user sh -c"
args="$@"

$run "whoami > $logfile 2>&1"
$run "date +'%Y-%m-%d %H:%M:%S' >> $logfile 2>&1"
$run "PATH=$PATH nohup $exec make --git-pull $args >> $logfile 2>&1 &"

