#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Std;

my %ami_config = (
    'linux i386' => 'ami-0133fd79', # linux-i386-4 (us-west-2)
    #'linux i386' => 'ami-67da141f', # linux-i386-3 (us-west-2)
    #'linux x86_64' => 'ami-13068c73', # linux-x64-2 (us-west-2)
    #'linux x86_64' => 'ami-24de105c', # linux-x64-3 (us-west-2)
    'linux x86_64' => 'ami-de32fca6', # linux-x64-4 (us-west-2)
);

my %opts;
getopts("ca:k:t:", \%opts) or
    die "Usage: $0 [-t <instance-type>] [-k <key-pair-name>] -a <arch> <user-data>\n";

my $arch = $opts{a}
    or die "No -a <arch> option specified.\n";

my $ami = $ami_config{$arch}
    or die "Unknown architecture $arch.\n";

my $keypair = $opts{k} || 'ortest';

my $instance_type = $opts{t};

if (!defined $instance_type) {
    #if ($arch =~ /x86_64/) {
    #$instance_type = 'm3.medium';

    #} else {
    #}
    $instance_type = 'c3.large';
}

my $user_data = join (" ", @ARGV)
    or die "No user data specified.\n";

my @cmd = ("ec2-run-instances", $ami, "-k", $keypair, "-d", $user_data,
        "--debug", "-t", $instance_type, #'--availability-zone', 'us-west-1b',
        '--region', 'us-west-2',
        '--instance-initiated-shutdown-behavior', 'terminate',
        '-g', 'ortest');

my $check = $opts{c};

warn "@cmd\n";

if ($check) {
    exit;
}

system @cmd;
