#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Std;

my %ami_config = (
    'linux i386' => 'ami-6cf6d729', # ortest-linux-i386-4 (us-west-1)
    #'linux i386' => 'ami-e27455a7', # ortest-linux-i386-3 (us-west-1)
    #'linux x86_64' => 'ami-e46d4ca1', # ortest-linux-x86_64-3 (us-west-1)
    'linux x86_64' => 'ami-b4f3d2f1', # ortest-linux-x86_64-4 (us-west-1)
);

my %opts;
getopts("ca:k:t:", \%opts) or
    die "Usage: $0 [-t <instance-type>] [-k <key-pair-name>] -a <arch> <user-data>\n";

my $arch = $opts{a}
    or die "No -a <arch> option specified.\n";

my $ami = $ami_config{$arch}
    or die "Unknown architecture $arch.\n";

my $keypair = $opts{k} || 'agentzh';

my $instance_type = $opts{t};

if (!defined $instance_type) {
    if ($arch eq 'linux x86_64') {
        #$instance_type = 'c1.medium';
        $instance_type = 'm2.xlarge';

    } else {
        $instance_type = 'c1.medium';
    }
}

my $user_data = join (" ", @ARGV)
    or die "No user data specified.\n";

my @cmd = ("ec2-run-instances", $ami, "-k", $keypair, "-d", $user_data,
        "--debug", "-t", $instance_type, '--availability-zone', 'us-west-1b',
        '--region', 'us-west-1',
        '--instance-initiated-shutdown-behavior', 'terminate',
        '-g', 'quick-start-1');

my $check = $opts{c};

print "@cmd\n";

if ($check) {
    exit;
}

system @cmd;

