#!/usr/bin/env perl

use strict;
use warnings;

use Getopt::Std;

my %ami_config = (
    'linux i386' => 'ami-f073a793', # linux-i386-8 (ap-southeast-1)
    #'linux i386' => 'ami-1ba66878', # linux-i386-7 (ap-southeast-1)
    #'linux x86_64' => 'ami-5214d931', # linux-x64-6 (ap-southeast-1)
    #'linux x86_64' => 'ami-1aa66879', # linux-x64-7 (ap-southeast-1)
    'linux x86_64' => 'ami-a871a5cb', # linux-x64-8 (ap-southeast-1)
);

my %opts;
getopts("ca:k:t:", \%opts) or
    die "Usage: $0 [-t <instance-type>] [-k <key-pair-name>] -a <arch> <user-data>\n";

my $arch = $opts{a}
    or die "No -a <arch> option specified.\n";

my $ami = $ami_config{$arch}
    or die "Unknown architecture $arch.\n";

my $keypair = $opts{k} || 'ortest';

my $instance_type = $opts{t};

if (!defined $instance_type) {
    #if ($arch eq 'linux x86_64') {
        #$instance_type = 'c1.medium';
        #$instance_type = 'c3.large';

        #} else {
        #$instance_type = 'c1.medium';
        #}
    $instance_type = 'c3.large';
}

my $user_data = join (" ", @ARGV)
    or die "No user data specified.\n";

my @cmd = ("ec2-run-instances", $ami, "-k", $keypair, "-d", $user_data,
        "--debug", "-t", $instance_type, #'--availability-zone', 'us-west-1b',
        '--region', 'ap-southeast-1',
        '--instance-initiated-shutdown-behavior', 'terminate',
        '-g', 'ortest');

my $check = $opts{c};

#print "@cmd\n";

if ($check) {
    exit;
}

system @cmd;
